name: Deploy App Preview
on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:
jobs:
  deploy-preview:
    if: ${{ !contains(github.event.head_commit.message, 'skip app preview') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "macos-latest"
            args: "--target universal-apple-darwin"
          - platform: "ubuntu-latest"
            args: ""
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable pnpm
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install dependencies
        run: pnpm i
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/dmg/*.dmg
            ${{ github.workspace }}/src-tauri/target/release/bundle/macos/*.app
            ${{ github.workspace }}/src-tauri/target/release/bundle/deb/*.deb
            ${{ github.workspace }}/src-tauri/target/release/bundle/appimage/*.appimage
            ${{ github.workspace }}/src-tauri/target/release/bundle/msi/*.msi
            ${{ github.workspace }}/src-tauri/target/release/bundle/nsis/*.exe
