name: Deploy Web Preview
on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:
jobs:
  deploy-preview:
    if: ${{ !contains(github.event.head_commit.message, 'skip web preview') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - name: Build app
        run: pnpm build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_DATABASE_URL: ${{ secrets.VITE_DATABASE_URL }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
          VITE_RECAPTCHA_ENTERPRISE_KEY: ${{ secrets.VITE_RECAPTCHA_ENTERPRISE_KEY }}
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LECTORNAUT }}"
          channelId: preview
          projectId: lectornaut
